/*
  THE WEB APP MANIFEST, and it exists for exactly one reason: SCOPE.

  Added to an iPhone's Home Screen, this app runs standalone — no address bar,
  no Safari chrome, like a native app. Which pages count as "the app" is decided
  by the manifest's `scope`, and WITHOUT A MANIFEST iOS infers one from whatever
  URL you happened to save. Save it while looking at /today and /today is the
  whole of the app: tapping Inbox or Tasks is then a trip OUT of it, and iOS
  hands those pages to its in-app browser instead — the overlay with the close
  button, the domain name and the reader controls along the top.

  That is the entire bug. `scope: '/'` says the app is the whole origin, so
  every tab stays inside it and none of that chrome appears.

  `start_url` is the root rather than a page, so launching from the Home Screen
  goes wherever the app's front door goes (lib/routes' HOME_PATH decides that,
  and the edge redirects `/` there) instead of pinning a second, stale answer to
  that question in here.

  NOTE FOR WHOEVER CHANGES THIS: iOS reads the manifest ONCE, when the icon is
  added. An installed Home Screen icon keeps the scope it was installed with, so
  a change here only reaches a phone that removes the icon and adds it again.
*/
export default function manifest() {
  return {
    name: 'Tasks',
    short_name: 'Tasks',
    description: 'Personal task management',
    start_url: '/',
    scope: '/',
    id: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#ffffff',
    // The emerald the mark and every "now" in the app are drawn in.
    theme_color: '#10b981',
    icons: [
      { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml' },
      // A real raster, for the platforms that will not take an SVG for a home
      // screen icon — iOS among them. Generated by app/apple-icon.js.
      { src: '/apple-icon', sizes: '180x180', type: 'image/png' },
      { src: '/apple-icon', sizes: '180x180', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
